#!/bin/bash

# Script: Generate API Index HTML
# Purpose: Generate review-artifacts/index.html with navigation structure for API review artifacts
# Matches Week 4 review artifact patterns

set -e  # Exit immediately on any error (fail-fast)

REVIEW_ARTIFACTS_DIR="review-artifacts"
INDEX_FILE="$REVIEW_ARTIFACTS_DIR/index.html"

echo "📝 Generating API review artifacts index.html..."

# Create review-artifacts directory if it doesn't exist
mkdir -p "$REVIEW_ARTIFACTS_DIR"

# Get current timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Generate index.html with navigation structure
cat > "$INDEX_FILE" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>API Review Artifacts - Week 5 Day-0</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
      background-color: #f5f5f5;
    }
    .container {
      background: white;
      border-radius: 8px;
      padding: 2rem;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 {
      color: #333;
      border-bottom: 3px solid #007acc;
      padding-bottom: 0.5rem;
    }
    h2 {
      color: #555;
      margin-top: 2rem;
    }
    .stats {
      display: flex;
      gap: 2rem;
      margin: 1.5rem 0;
      padding: 1rem;
      background: #f8f9fa;
      border-radius: 4px;
    }
    .stat-item {
      flex: 1;
    }
    .stat-label {
      font-size: 0.9rem;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .stat-value {
      font-size: 2rem;
      font-weight: bold;
      color: #007acc;
      margin-top: 0.25rem;
    }
    .artifact-section {
      margin: 2rem 0;
      padding: 1.5rem;
      border: 1px solid #ddd;
      border-radius: 4px;
      background: #fafafa;
    }
    .artifact-section h3 {
      margin-top: 0;
      color: #333;
    }
    .artifact-links {
      display: flex;
      gap: 1rem;
      margin-top: 1rem;
      flex-wrap: wrap;
    }
    .artifact-link {
      display: inline-block;
      padding: 0.75rem 1.5rem;
      background: #007acc;
      color: white;
      text-decoration: none;
      border-radius: 4px;
      transition: background 0.2s;
    }
    .artifact-link:hover {
      background: #005a9e;
    }
    .artifact-link.secondary {
      background: #6c757d;
    }
    .artifact-link.secondary:hover {
      background: #545b62;
    }
    .metadata {
      margin-top: 2rem;
      padding: 1rem;
      background: #e9ecef;
      border-radius: 4px;
      font-size: 0.9rem;
      color: #666;
    }
    .metadata-item {
      margin: 0.5rem 0;
    }
    .metadata-label {
      font-weight: bold;
      color: #333;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>📦 API Review Artifacts</h1>
    <p>Week 5 Day-0: API Scaffolding and Spec-First Setup</p>

    <div class="stats">
      <div class="stat-item">
        <div class="stat-label">Artifacts</div>
        <div class="stat-value">3</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">Coverage Reports</div>
        <div class="stat-value">2</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">Status</div>
        <div class="stat-value">✅</div>
      </div>
    </div>

    <div class="artifact-section">
      <h3>📋 OpenAPI Specification</h3>
      <p>API specification in OpenAPI 3.1 format defining endpoints, request/response schemas, and validation rules.</p>
      <div class="artifact-links">
        <a href="openapi.yaml" class="artifact-link" download>📄 Download OpenAPI Spec</a>
        <a href="openapi.yaml" class="artifact-link secondary" target="_blank">👁️ View OpenAPI Spec</a>
      </div>
    </div>

    <div class="artifact-section">
      <h3>📊 Test Coverage Reports</h3>
      <p>Code coverage reports generated by Vitest with v8 coverage provider. Includes LCOV format and interactive HTML reports.</p>
      <div class="artifact-links">
        <a href="api-coverage/index.html" class="artifact-link" target="_blank">📈 View Coverage Report</a>
        <a href="api-coverage/lcov.info" class="artifact-link secondary" download>📄 Download LCOV Data</a>
      </div>
    </div>

    <div class="metadata">
      <div class="metadata-item">
        <span class="metadata-label">Generated:</span> $TIMESTAMP
      </div>
      <div class="metadata-item">
        <span class="metadata-label">Coverage Tool:</span> Vitest v8
      </div>
      <div class="metadata-item">
        <span class="metadata-label">Specification Format:</span> OpenAPI 3.1
      </div>
      <div class="metadata-item">
        <span class="metadata-label">Artifact Name:</span> review-packet-api
      </div>
    </div>
  </div>
</body>
</html>
EOF

# Verify index.html was created
if [ ! -f "$INDEX_FILE" ]; then
  echo "❌ Failed to generate index.html"
  exit 1
fi

# Basic validation
if ! grep -q "<html" "$INDEX_FILE"; then
  echo "❌ Generated index.html may not be valid HTML"
  exit 1
fi

echo "✅ API review artifacts index.html generated successfully"
echo "   Location: $INDEX_FILE"
