---
name: Bug
description: Report a bug or issue with the API
labels: [bug]
body:
  - type: textarea
    id: repro
    attributes:
      label: Repro Steps
  - type: input
    id: spec
    attributes:
      label: Spec/Contract Link (if applicable)
---