---
name: Feature
description: Create a feature request for a new API endpoint or enhancement
labels: [feature]
body:
  - type: input
    id: spec
    attributes:
      label: Spec URL
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
  - type: textarea
    id: tasks
    attributes:
      label: Tasks (SpecKit/tasks export allowed)
---