---
name: Feature
description: Create a feature request for a new API endpoint or enhancement
labels: [feature]
body:
  - type: input
    id: spec
    attributes:
      label: Spec URL
      placeholder: e.g., specs/026-title-week-5/spec.md
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: Describe the acceptance criteria for this feature
  - type: textarea
    id: tasks
    attributes:
      label: Tasks (SpecKit/tasks export allowed)
      placeholder: Paste your task checklist here
    validations:
      required: true
---