name: Create Wednesday Sub-Issues

on:
  push:
    branches:
      - feature/PRI-289-wednesday-ui-polishing
    paths:
      - 'specs/013-title-wednesday-spec/tasks.md'
  workflow_dispatch:

jobs:
  create-sub-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Linear Sub-Issues
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
        run: |
          echo "🚀 Creating 24 sub-issues under PRI-289..."
          node scripts/create-wednesday-sub-issues.js
