name: linear-tasks-sync

on:
  push:
    branches:
      - '**'
    paths:
      - 'specs/*/tasks.md'
      - 'specs/*/.linear-parent'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed spec folders
        id: detect
        run: |
          set -euo pipefail
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"
          TASK_FILES=$(git diff --name-only "$BEFORE" "$AFTER" -- 'specs/*/tasks.md')
          PARENT_FILES=$(git diff --name-only "$BEFORE" "$AFTER" -- 'specs/*/.linear-parent')
          # Derive unique spec directories
          DIRS=$(printf "%s\n%s\n" "$TASK_FILES" "$PARENT_FILES" | awk -F/ '/^specs\//{print $1"/"$2"/"$3}' | sort -u | tr '\n' ' ' | sed 's/ *$//')
          echo "spec_dirs=$DIRS" >> $GITHUB_OUTPUT
          if [ -z "$DIRS" ]; then
            echo "No relevant spec folder changes detected." >> $GITHUB_STEP_SUMMARY
          else
            echo "Spec folders changed: $DIRS" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Setup Node
        if: ${{ steps.detect.outputs.spec_dirs != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sync each changed spec folder to Linear
        if: ${{ steps.detect.outputs.spec_dirs != '' }}
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          for dir in ${{ steps.detect.outputs.spec_dirs }}; do
            file="$dir/tasks.md"
            parent=""
            if [ -f "$dir/.linear-parent" ]; then
              parent=$(cat "$dir/.linear-parent" | tr -d '\n' | tr -d '\r' | xargs)
            fi
            if [ -z "$parent" ] && [[ "$GITHUB_REF_NAME" =~ ([A-Za-z]+-[0-9]+) ]]; then
              parent="${BASH_REMATCH[1]}"
            fi
            if [ -z "$parent" ]; then
              echo "Skipping $file: cannot determine parent issue id" >> $GITHUB_STEP_SUMMARY
              continue
            fi
            echo "Sync: $file -> $parent" >> $GITHUB_STEP_SUMMARY
            TASKS_FILE="$file" LINEAR_PARENT_IDENTIFIER="$parent" node scripts/linear-sync.js
          done


