name: linear-tasks-sync

on:
  push:
    branches:
      - '**'
    branches-ignore:
      - development
      - main
    paths:
      - 'specs/*/tasks.md'
      - 'specs/*/.linear-parent'
  workflow_dispatch:

jobs:
  sync:
    # Only run for feature branches (e.g., feature/... or ...-feat-...)
    if: >-
      github.ref_type == 'branch' &&
      (startsWith(github.ref_name, 'feature/') || contains(github.ref_name, '-feat-'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed tasks files
        id: detect
        run: |
          set -euo pipefail
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"
          ZERO_SHA="0000000000000000000000000000000000000000"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "$ZERO_SHA" ] || ! git cat-file -e "$BEFORE"^{commit} 2>/dev/null; then
            # First commit or new branch push: diff against this commit only
            FILES=$(git diff-tree --no-commit-id --name-only -r "$AFTER" -- 'specs/*/tasks.md' 'specs/*/.linear-parent' | tr '\n' ' ' | sed 's/ *$//')
          else
            FILES=$(git diff --name-only "$BEFORE" "$AFTER" -- 'specs/*/tasks.md' 'specs/*/.linear-parent' | tr '\n' ' ' | sed 's/ *$//')
          fi
          TASKS=""
          for f in $FILES; do
            if [[ "$f" == */tasks.md ]]; then
              TASKS+="$f "
            elif [[ "$f" == */.linear-parent ]]; then
              TASKS+="${f%/.linear-parent}/tasks.md "
            fi
          done
          TASKS=$(echo "$TASKS" | sed 's/ *$//')
          echo "changed=$TASKS" >> $GITHUB_OUTPUT
          if [ -z "$TASKS" ]; then
            echo "No tasks.md changes detected." >> $GITHUB_STEP_SUMMARY
          else
            echo "Changed files: $TASKS" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Setup Node
        if: ${{ steps.detect.outputs.changed != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sync each changed tasks file to Linear
        if: ${{ steps.detect.outputs.changed != '' }}
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          LINEAR_TEAM_NAME: Prince Training
          LINEAR_PROJECT_NAME: Training-Prince
        run: |
          set -euo pipefail
          for file in ${{ steps.detect.outputs.changed }}; do
            dir=$(dirname "$file")
            parent=""
            if [ -f "$dir/.linear-parent" ]; then
              parent=$(cat "$dir/.linear-parent" | tr -d '\n' | tr -d '\r' | xargs)
            fi
            if [ -z "$parent" ] && [[ "$GITHUB_REF_NAME" =~ ([A-Za-z]+-[0-9]+) ]]; then
              parent="${BASH_REMATCH[1]}"
            fi
            if [ -z "$parent" ]; then
              echo "Skipping $file: cannot determine parent issue id" >> $GITHUB_STEP_SUMMARY
              continue
            fi
            echo "Sync: $file -> $parent" >> $GITHUB_STEP_SUMMARY
            TASKS_FILE="$file" LINEAR_PARENT_IDENTIFIER="$parent" node scripts/linear-sync.js
          done


