name: pr-title-lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR title starts with PRI-<number>
        uses: actions/github-script@v7
        with:
          script: |
            const raw = context.payload.pull_request.title || '';
            const title = raw.trim();
            core.info(`PR title: "${title}"`);
            const m = title.match(/^([Pp][Rr][Ii]-\d+)(?=[:\s]|$)/);
            if (!m) {
              core.setFailed('PR title must start with your team key: PRI-123: Short description');
            }
