name: Build Review Packet

on:
  workflow_dispatch:
  push:
    branches: [ development ]

jobs:
  build-review-packet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      # Run tests for each app and output coverage to a unique directory
      - name: Run Hello Tests & Collect Coverage
        run: npm test -- tests/hello.*.test.js --coverage --output-dir=coverage-hello
      - name: Run Stopwatch Tests & Collect Coverage
        run: npm test -- tests/stopwatch.*.test.js --coverage --output-dir=coverage-stopwatch
      - name: Run Temp Converter Tests & Collect Coverage
        run: npm test -- tests/temp-converter.*.test.js --coverage --output-dir=coverage-temp
      - name: Run Expense Tests & Collect Coverage
        run: npm test -- tests/expense.*.test.js --coverage --output-dir=coverage-expense
      - name: Run To-Do Tests & Collect Coverage
        run: npm test -- tests/todo.*.test.js --coverage --output-dir=coverage-todo
      - name: Run Quote Tests & Collect Coverage
        run: npm test -- tests/quote.*.test.js --coverage --output-dir=coverage-quote

      # Prepare the artifact structure
      - name: Prepare artifact directories
        run: |
          mkdir -p review-artifacts
          mv coverage-* review-artifacts/

      # (We will add the index.html generation in the next step)

      - name: Generate review.md
        run: |
          echo "## Review Packet" > review.md
          echo "Generated: $(date)" >> review.md

      # Upload the artifact
      - name: Upload Review Packet Artifact
        uses: actions/upload-artifact@v4
        with:
          name: review-packet
          path: |
            review.md
            review-artifacts/