name: Sync to Public Mirror

on:
  push:
    branches:
      - main
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Prefer SSH deploy key if provided
      - name: Set up SSH (DEPLOY_KEY)
        if: ${{ env.DEPLOY_KEY != '' }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.DEPLOY_KEY }}

      - name: Push to Public Mirror via SSH
        if: ${{ env.DEPLOY_KEY != '' }}
        run: |
          git remote add mirror git@github.com:Maximus-Technologies-Uganda/training-prince-mirror.git
          git push --force --all mirror
          git push --force --tags mirror

      # If DEPLOY_KEY is missing, fail with a helpful message
      - name: Fail due to missing secrets
        if: ${{ env.DEPLOY_KEY == '' }}
        run: |
          echo "Error: Missing DEPLOY_KEY secret. Add your SSH private key as repo secret DEPLOY_KEY and the matching PUBLIC key as a Deploy key (write) on the mirror repo." 1>&2
          exit 1
