name: Sync to Public Mirror

on:
  push:
    branches:
      - main
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Prefer SSH deploy key if provided
      - name: Set up SSH (DEPLOY_KEY)
        if: ${{ env.DEPLOY_KEY != '' }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.DEPLOY_KEY }}

      - name: Push to Public Mirror via SSH
        if: ${{ env.DEPLOY_KEY != '' }}
        run: |
          git remote add mirror git@github.com:Maximus-Technologies-Uganda/training-prince-mirror.git
          git push --force --all mirror
          git push --force --tags mirror

      # Fallback to HTTPS with PAT if MIRROR_TOKEN is set
      - name: Push to Public Mirror via HTTPS token
        if: ${{ env.DEPLOY_KEY == '' && env.MIRROR_TOKEN != '' }}
        run: |
          set -euo pipefail
          git remote add mirror https://x-access-token:${{ env.MIRROR_TOKEN }}@github.com/Maximus-Technologies-Uganda/training-prince-mirror.git
          git push --force --all mirror
          git push --force --tags mirror

      # If neither secret is set, fail with a helpful message
      - name: Fail due to missing secrets
        if: ${{ env.DEPLOY_KEY == '' && env.MIRROR_TOKEN == '' }}
        run: |
          echo "Error: Missing secrets. Set DEPLOY_KEY (SSH) or MIRROR_TOKEN (HTTPS PAT)." 1>&2
          exit 1
