name: Sync to Public Mirror

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Public Mirror (HTTPS with token)
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${MIRROR_TOKEN:-}" ]; then
            echo "Missing MIRROR_TOKEN secret" >&2
            exit 1
          fi
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/Maximus-Technologies-Uganda/training-prince-mirror.git
          git push --force --all mirror
          git push --force --tags mirror
