name: Sync to Public Mirror

on:
  push:
    branches:
      - main
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Public Mirror
        run: |
          git push --force "https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/Maximus-Technologies-Uganda/training-prince-mirror.git" --all
          git push --force "https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/Maximus-Technologies-Uganda/training-prince-mirror.git" --tags