name: Sync to Public Mirror - Key Generation

on:
  workflow_dispatch: # This allows us to run it manually

jobs:
  generate-key:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SSH key
        run: |
          ssh-keygen -t ed25519 -N "" -f ./deploy_key
          echo " "
          echo "ACTION REQUIRED: Copy the entire public key block below"
          echo "========================================================"
          cat ./deploy_key.pub
          echo "========================================================"
          echo " "
